spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true
        ephemeral: true

    gateway:
      routes:
        - id: user-service-router
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: file_service-router
          uri: lb://file-service
          predicates:
            - Path=/file/**
server:
  port: 8080
