spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: video-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fc
    username: fc_user
    password: fc_password

server:
  port: 0
